language: node_js
sudo: required
node_js:
  - 8.11.1
cache:
  directories:
    - node_modules
script:
    - ./deploy.sh
branch: master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $0870b91e3c93dc638524369898c76a158dadee2b
  local-dir: ./docs/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master